---
- name: Download pipeline templates
  hosts: localhost
  connection: local
  vars_files:
    - repo_config.yml
  tasks:
    - name: "Download templates"
      ansible.builtin.get_url:
        url: file:///Users/yuna/Documents/projects/YunaBraska/.github/ansible/ci.tmpl.yml
#        url: https://www.w3.org/TR/PNG/iso_8859-1.txt
        dest: ./ci.tmpl.yml.download
    - name: Render templates
      ansible.builtin.template:
        src: ./ci.tmpl.yml.download
        dest: ci.yml
    - name: "Clean up downloaded files"
      ansible.builtin.file:
        path: ./ci.tmpl.yml.download
        state: absent
