name: CheckContentOwnerProcessor

on:
  workflow_call:

jobs:
  build_2:
    runs-on: ubuntu-latest
    steps:
      - name: "Check Permission"
        run: |
          if [ "$GITHUB_ACTOR" != "YunaBraska" ]; then echo "Permission denied for user [$GITHUB_ACTOR]"; exit 1; fi
      - name: "Print Variables"
        run:  env
