name: ContentOwnerCheck

on:
  workflow_dispatch:
  push:
    branches: [ feat/0/reusable_workflow ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Print Variables"
        run: |
          echo "GITHUB_REPOSITORY_OWNER [$GITHUB_REPOSITORY_OWNER]"
          echo "REPOSITORY [$GITHUB.REPOSITORY]"
          echo "REPOSITORY_OWNER [$GITHUB.REPOSITORY_OWNER]"
          echo "GitHub SHA: $GITHUB_SHA"
          echo "GITHUB_PATH [$GITHUB_PATH]"
          echo "RUNNER_OS [$RUNNER_OS]"
          echo "GITHUB_JOB [$GITHUB_JOB]"
          echo "RUNNER_NAME [$RUNNER_NAME]"
          echo "GITHUB_RUN_ID [$GITHUB_RUN_ID]"
          echo "GITHUB_RUN_NUMBER [$GITHUB_RUN_NUMBER]"
          echo "GITHUB_SERVER_URL [$GITHUB_SERVER_URL]"
          echo "GITHUB_WORKFLOW [$GITHUB_WORKFLOW]"
          echo "GITHUB_WORKSPACE [$GITHUB_WORKSPACE]"
          echo "RUNNER_ARCH [$RUNNER_ARCH]"
          echo "GITHUB_ACTOR [$GITHUB_ACTOR]"
          echo "GITHUB_API_URL [$GITHUB_API_URL]"
          echo "GITHUB_ACTIONS [$GITHUB_ACTIONS]"
          echo "GITHUB_REF [$GITHUB_REF]"
          echo "GITHUB_REF_NAME [$GITHUB_REF_NAME]"
          echo "GITHUB_BASE_REF [$GITHUB_BASE_REF]"
          echo "GITHUB_HEAD_REF [$GITHUB_HEAD_REF]"
          echo "GITHUB_EVENT_NAME [$GITHUB_EVENT_NAME]"
          echo "GITHUB_EVENT_PATH [$GITHUB_EVENT_PATH]"
          echo "GITHUB_ACTION_REPOSITORY [$GITHUB_ACTION_REPOSITORY]"
          echo "GITHUB_RETENTION_DAYS [$GITHUB_RETENTION_DAYS]"
          echo "GITHUB_RUN_ATTEMPT [$GITHUB_RUN_ATTEMPT]"
          echo "GITHUB_CONTEXT [$GITHUB_CONTEXT]"
          if [ "$GITHUB_ACTOR" != "YunaBraska1" ]; then echo "Permission denied with user [$GITHUB_ACTOR]"; exit 1; fi
