name: ContentOwnerCheck

on:
  workflow_dispatch:
  push:
    branches: [ feat/0/reusable_workflow ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Print Variables"
        run: |
          echo "GITHUB_REPOSITORY_OWNER [${{ env.GITHUB_REPOSITORY_OWNER }}]"
          echo "GITHUB_RUN_ID [${{ env.GITHUB_REF_NAME }}]"
          echo "GITHUB_RUN_ID [$env.GITHUB_REF_NAME]"
          echo "GITHUB_RUN_ID [env.GITHUB_REF_NAME]"
          echo "GITHUB_RUN_ID $env.GITHUB_REF_NAME"
