name: "Trigger: On Tag"

on:
  workflow_dispatch:
  push:
    # Pattern matched against refs/tags
    tags:
      - '*'  # Push events to every tag not containing /
      - '**' # Push events to every tag including hierarchical tags like v1.0/beta
      - '***'
      - '****'

jobs:
  maven_github_release:
    name: "maven"
    uses: YunaBraska/YunaBraska/.github/workflows/wc_maven_github_release.yml@feat/0/reusable_workflow
    needs: maven_tag
    # has_pom                     ${{needs.maven_test.outputs.has_pom}}
    # changelog                   ${{needs.maven_test.outputs.changelog}}
    # java_version                ${{needs.maven_test.outputs.java_version}}
    # latest_tag                  ${{needs.maven_test.outputs.latest_tag}}
    # second_latest_tag           ${{needs.maven_test.outputs.second_latest_tag}}
    # semver_strategy             ${{needs.maven_test.outputs.semver_strategy}}
  maven_central_release:
    name: "maven"
    uses: YunaBraska/YunaBraska/.github/workflows/wc_maven_central_release.yml@feat/0/reusable_workflow
    needs: maven_tag
    # has_pom                     ${{needs.maven_test.outputs.has_pom}}
    # java_version                ${{needs.maven_test.outputs.java_version}}
