name: CI_MVN

on:
  workflow_dispatch:
    inputs:
      repository:
        type: string
        description: "[repository] [default:${GITHUB_REPOSITORY}] (e.g. my-org/my-repo)"
        required: false
      branch:
        type: string
        description: "[branch] [default:${GITHUB_REF}] (e.g. my-branch)"
        required: false
      tag_new:
        type: string
        description: "[tag_new] [default:''] (e.g. 1.2.3-RC4+Meta5)"
        required: false
      increase:
        type: string
        options:
          - major
          - minor
          - patch
          - rc
          - meta
        description: "[increase] fallback to increase the version [default:rc] (e.g. major, minor, patch, rc, meta)"
        required: false
      codeclimate_id:
        type: string
        description: "[codeclimate_id] will send code cov to codeclimate [default:'']"
        required: false
  workflow_call:
    inputs:
      repository:
        type: string
        description: "[repository] [default:${GITHUB_REPOSITORY}] (e.g. my-org/my-repo)"
        required: false
      branch:
        type: string
        description: "[branch] [default:${GITHUB_REF}] (e.g. my-branch)"
        required: false
      tag_new:
        type: string
        description: "[tag_new] [default:''] (e.g. 1.2.3-RC4+Meta5)"
        required: false
      increase:
        type: string
        description: "[increase] fallback to increase the version [default:rc] (e.g. major, minor, patch, rc, meta)"
        required: false
      codeclimate_id:
        type: string
        description: "[codeclimate_id] will send code cov to codeclimate [default:'']"
        required: false
  repository_dispatch:
    types: [ EVENT_CI_MVN ]

jobs:
  maven:
    name: "Maven Pipeline"
    runs-on: ubuntu-latest

    steps:
      - name: "Read Inputs"
        id: "info_input"
        run: |
          branch="${branch_A:-${branch_B:-${branch_C:-${GITHUB_REF}}}}"
          repository="${repository_A:-${repository_B:-${repository_C:-${GITHUB_REPOSITORY}}}}"
          tag_new="${tag_new_A:-${tag_new_B:-${tag_new_C}}}"
          increase="${increase_A:-${increase_B:-${increase_C:-rc}}}"
          codeclimate_id="${codeclimate_id_A:-${codeclimate_id_B:-${codeclimate_id_C:-${{secrets.CC_TEST_REPORTER_ID}}}}}"
          trigger_cc_test_id=$(if [[ "$codeclimate_id" == "" ]]; then echo "true"; else echo "false"; fi)
          
          echo "branch [$branch]"
          echo "repository [$repository]"
          echo "tag_new [$tag_new]"
          echo "increase [$increase]"
          echo "trigger_cc_test_id [$trigger_cc_test_id]"
          
          echo "::set-output name=branch::$branch"
          echo "::set-output name=repository::$repository"
          echo "::set-output name=tag_new::$tag_new"
          echo "::set-output name=increase::$increase"
          echo "::set-output name=codeclimate_id::$tcodeclimate_id"
          echo "::set-output name=trigger_cc_test_id::$trigger_cc_test_id"
        env:
          branch_A: ${{ inputs.branch }}
          branch_B: ${{ github.event.inputs.branch }}
          branch_C: ${{ github.event.client_payload.branch }}

          repository_A: ${{ inputs.repository }}
          repository_B: ${{ github.event.inputs.repository }}
          repository_C: ${{ github.event.client_payload.repository }}

          tag_new_A: ${{ inputs.tag_new }}
          tag_new_B: ${{ github.event.inputs.tag_new }}
          tag_new_C: ${{ github.event.client_payload.tag_new }}

          increase_A: ${{ inputs.increase }}
          increase_B: ${{ github.event.inputs.increase }}
          increase_C: ${{ github.event.client_payload.increase }}

          codeclimate_id_A: ${{ inputs.codeclimate_id }}
          codeclimate_ide_B: ${{ github.event.inputs.codeclimate_id }}
          codeclimate_id_C: ${{ github.event.client_payload.codeclimate_id }}
      - name: "Checkout Repository"
        uses: actions/checkout@v3
        with:
          ref: ${{ steps.info_input.outputs.branch }}
          repository: ${{ steps.info_input.outputs.repository }}
          token: ${{ secrets.CI_TOKEN }}
      - name: "Setup Python"
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: "Detect Java Version"
        id: "detect_java"
        run: |
          echo "Python [$(python --version)]"
          echo "Python3 [$(python3 --version)]"
          pip3 install lxml
          wget -nc -nv https://raw.githubusercontent.com/YunaBraska/YunaBraska/main/.github/scripts/python/functions/xml_reader.py -P target
          chmod +x target/xml_reader.py
          java_version=$(target/xml_reader.py --pjv)
          echo "java_version [$java_version]"
          echo "::set-output name=java_version::$java_version"
          rm -rf target/git_analyze.py target/semver.py target/xml_reader.py
      - name: "Setup Java"
        uses: actions/setup-java@v1
        with:
          java-version: ${{ steps.detect_java.outputs.java_version }}
      - name: "Preparation"
        run: |
          ./mvnw -B -N io.takari:maven:wrapper
          ./mvnw -B -q versions:update-properties -DgenerateBackupPoms=false
          ./mvnw dependency:resolve-plugins -q -U
          ./mvnw dependency:resolve -q -U
      - name: "Run Test"
        run: |
          ./mvnw -B clean package
      - name: "Execute Scripts"
        id: "repo_analyze"
        run: |
          mkdir -p target
          wget -nc -nv https://raw.githubusercontent.com/YunaBraska/YunaBraska/main/.github/scripts/python/functions/semver.py -P target
          wget -nc -nv https://raw.githubusercontent.com/YunaBraska/YunaBraska/main/.github/scripts/python/functions/git_analyze.py -P target
          chmod +x target/git_analyze.py target/semver.py
          
          git config --global user.name 'Kira'
          git config --global user.email 'yuna-@web.de'
          git_analyze=$(target/git_analyze.py --set_tag=${{ steps.info_input.outputs.tag_new }} --increase=${{ steps.info_input.outputs.increase }} --do_tag=tag_needed --do_update_pom=tag_needed --do_commit=has_changes)
          echo "git_analyze [$git_analyze]"
          
          has_changes=$(echo $git_analyze | jq '.has_changes')
          tag_needed=$(echo $git_analyze | jq '.tag_needed')
          tag_new=$(echo $git_analyze | jq '.tag_new')
          commit_msg=$(echo $git_analyze | jq '.commit_msg')
          is_branch_default=$(echo $git_analyze | jq '.is_branch_default')
          trigger_release=$(if [[ "$tag_needed" == "true" && "$tag_needed" == "$is_branch_default" ]]; then echo "true"; else echo "false"; fi)

          echo "has_changes [$has_changes]"
          echo "tag_needed [$tag_needed]"
          echo "tag_new [$tag_new]"
          echo "commit_msg [$commit_msg]"
          echo "is_branch_default [$is_branch_default]"
          echo "trigger_release [$trigger_release]"

          echo "::set-output name=has_changes::$has_changes"
          echo "::set-output name=tag_needed::$tag_needed"
          echo "::set-output name=tag_new::$tag_new"
          echo "::set-output name=commit_msg::$commit_msg"
          echo "::set-output name=is_branch_default::$is_branch_default
          echo "::set-output name=trigger_release::$trigger_release
          
          echo $commit_msg > target/release.log
          rm -rf target/git_analyze.py target/semver.py
      - name: "Test Output"
        run: |
          echo "trigger_release [$trigger_release]"
          echo "env.trigger_release [${{ env.trigger_release }}]"
          echo "steps.repo_analyze.outputs.trigger_release [${{ steps.repo_analyze.outputs.trigger_release }}]"
          echo "needs.repo_analyze.outputs.trigger_release [${{ needs.repo_analyze.outputs.trigger_release }}]"
          echo "needs.maven.outputs.trigger_release [${{ needs.maven.outputs.trigger_release }}]"
      - name: "Create release"
        if: steps.repo_analyze.outputs.trigger_release == 'true'
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.maven.outputs.new_version }}
          artifacts: "target/*.jar,build/*.jar"
          generateReleaseNotes: true
          bodyFile: target/release.log
          token: ${{ secrets.GITHUB_TOKEN }}
          repo: ${{ steps.info_input.outputs.repository }}
      - name: "Publish code quality"
        uses: paambaati/codeclimate-action@v3.0.0
        if: steps.info_input.outputs.trigger_cc_test_id  == 'true_skipped'
        env:
          CC_TEST_REPORTER_ID: ${{ steps.info_input.outputs.codeclimate_id }}
          JACOCO_SOURCE_PATH: "${{github.workspace}}/src/main/java"
        with:
          coverageLocations: ${{github.workspace}}/target/site/jacoco/jacoco.xml:jacoco
      - name: "Remove workflow files"
        run: |
          rm -rf coverage* &>/dev/null || true
          rm -rf codeclimate* &>/dev/null || true
          rm -rf ./*reporter* &>/dev/null || true




