name: "[RE] Update Maven"

on:
  workflow_call:
    # Map the workflow outputs to job outputs
    outputs:
      java_version:
        description: "The first output string"
        value: ${{ jobs.my_job.outputs.java_version }}
jobs:
  my_job:
    runs-on: ubuntu-latest
    # Map the job outputs to step outputs
    outputs:
      java_version: ${{ steps.my_step.outputs.java_version }}
    steps:
      - name: "Check Permission"
        run: |
          if [ "$GITHUB_ACTOR" != "YunaBraska" ]; then echo "Permission denied for user [$GITHUB_ACTOR]"; exit 1; fi
      - name: "Print Variables"
        run: env
      - name: "Checkout"
        uses: actions/checkout@v3
      - name: "Read java version"
        id: "my_step"
        run: |
          java_version=$(./mvnw help:evaluate -Dexpression=java-version -q -DforceStdout)
          echo "Pom java version [$java_version]"
          echo ::set-output name=java_version::"$java_version"
      - name: "Update Maven & Dependencies"
        id: "maven"
        run: |
          echo "java version [${{steps.my_step.outputs.java_version}}]"
          ./mvnw -B -q -N io.takari:maven:wrapper
          ./mvnw -B -q versions:update-parent -DgenerateBackupPoms=false
          ./mvnw -B -q versions:update-properties -DgenerateBackupPoms=false
      - name: "Detect changes"
        id: "git"
        run: |
          has_changes=$(if [[ $(git status --porcelain) ]]; then echo "true"; else echo "false";fi)
          echo "number of changes [$(git status --porcelain | wc -l)]"
          echo "has_changes [$has_changes]"
          echo ::set-output name=has_changes::"$has_changes"
      - name: "Print changes"
        run: |
          echo "has_changes [${{steps.git.outputs.has_changes}}]"
      - name: "Test changes"
        if: steps.git.outputs.has_changes == 'true'
        run: |
          ./mvnw -B -q clean verify
      - name: "Push changes"
        if: steps.git.outputs.has_changes == 'true'
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore: Updated maven wrapper"
          commit_user_name: Kira
          commit_user_email: kira@yuna.berlin
          commit_author: Kira <kira@yuna.berlin>
          skip_dirty_check: true
          skip_fetch: true
          skip_checkout: true
          disable_globbing: true
          create_branch: false
          
