name: "Trigger: On Tag"

on:
  push:
    tags:
      - '*'
      - '**'

jobs:
  maven_github_release:
    name: "maven"
    uses: YunaBraska/YunaBraska/.github/workflows/wc_maven_github_release.yml@feat/0/reusable_workflow
    # has_pom                     ${{needs.maven_test.outputs.has_pom}}
    # changelog                   ${{needs.maven_test.outputs.changelog}}
    # java_version                ${{needs.maven_test.outputs.java_version}}
    # latest_tag                  ${{needs.maven_test.outputs.latest_tag}}
    # second_latest_tag           ${{needs.maven_test.outputs.second_latest_tag}}
    # semver_strategy             ${{needs.maven_test.outputs.semver_strategy}}
  maven_central_release:
    name: "maven"
    uses: YunaBraska/YunaBraska/.github/workflows/wc_maven_central_release.yml@feat/0/reusable_workflow
    # has_pom                     ${{needs.maven_test.outputs.has_pom}}
    # java_version                ${{needs.maven_test.outputs.java_version}}
  do_something:
    needs: maven_central_release
    runs-on: ubuntu-latest
    steps:
      - name: "Set up JDK"
        uses: actions/setup-java@main
        with:
          java-version: ${{needs.maven_central_release.outputs.java_version}}
          distribution: 'adopt'
