NAME "TRIGGER_TEST_WORKFLOW"
on:
  workflow_dispatch:

jobs:
  workflow_call:
    runs-on: ubuntu-latest
    steps:
      - name: workflow_call
        uses: YunaBraska/YunaBraska/.github/workflows/test_workflow.yml@main
        with:
          my_field: "BBB"
      - name: repository_dispatch
        uses: passeidireto/trigger-external-workflow-action@main
        env:
          PAYLOAD_test_event: "CCC"
        with:
          repository: YunaBraska/YunaBraska
          event: test_event
          github_pat: ${{ secrets.GITHUB_TOKEN }}

