name: TRIGGER_TEST

on:
  workflow_dispatch:


jobs:
  run_workflow_call1:
    name: workflow_call1
    uses: YunaBraska/YunaBraska/.github/workflows/test_workflow.yml@mainn
    with:
      my_field: "BBB"
  run_workflow_call2:
    name: workflow_call2
    uses: YunaBraska/YunaBraska/.github/workflows/RE_JobOutputs.yml@main
  run_repository_dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: repository_dispatch
        uses: passeidireto/trigger-external-workflow-action@main
        env:
          PAYLOAD_my_field: "CCC"
        with:
          repository: YunaBraska/YunaBraska
          event: test_event
          github_pat: ${{ secrets.CI_TOKEN }}

