name: "[WC] Test Maven"
#description: "Runs maven tests && publish changes e.g. version.txt"

on:
  workflow_call:
    inputs:
      ref:
        type: string
        description: "[ref] e.g. branch, tag or commit to checkout [default: github_ref_name || github_head_ref ]"
        required: false
    secrets:
      CC_TEST_REPORTER_ID:
        description: "Code Climate Id for test coverage and quality checks"
        required: false
    # Map the workflow outputs to job outputs
    outputs:
      has_pom:
        description: "[Boolean] if pom file exists"
        value: ${{ jobs.test.outputs.has_pom }}
      has_changes:
        description: "[Boolean] if git status has changes"
        value: ${{ jobs.test.outputs.has_changes }}
      java_version:
        description: "[String] java version from pom file"
        value: ${{ jobs.test.outputs.java_version }}
      project_version:
        description: "[String] project version from pom file"
        value: ${{ jobs.test.outputs.project_version }}
      has_publish_to_code_climate:
        description: "[String] if code quality is pushed to code climate"
        value: ${{ jobs.test.outputs.has_publish_to_code_climate }}
jobs:
  test:
    runs-on: ubuntu-latest
    # Map the job outputs to step outputs
    outputs:
      has_pom: ${{ steps.pom.outputs.has_pom }}
      has_changes: ${{ steps.git.outputs.has_changes }}
      java_version: ${{ steps.java.outputs.java_version }}
      project_version: ${{ steps.java.outputs.project_version }}
      has_publish_to_code_climate: ${{ steps.java.outputs.has_publish_to_code_climate }}
    steps:
      - name: "Validate Input"
        id: "inputs"
        run: |
          if [ "$GITHUB_ACTOR" != "YunaBraska" ]; then echo "Permission denied for user [$GITHUB_ACTOR]"; exit 1; fi
          
          ref_default=${{ github.ref_name || github.head_ref }}
          ref="${ref_A:-${ref_B:-${ref_C:-${ref_default}}}}"
          
          echo "ref [$ref]"
          
          echo "::set-output name=ref::$ref"
        env:
          ref_A: ${{ inputs.ref }}
          ref_B: ${{ github.event.inputs.ref }}
          ref_C: ${{ github.event.client_payload.ref }}
      - name: "Checkout"
        uses: actions/checkout@main
        with:
          ref: ${{ steps.inputs.outputs.ref }}
      - name: "Locate POM"
        id: "pom"
        run: |
          has_pom=$([ -e "pom.xml" ] && echo "true" || echo "false") 
          echo "has_pom [$has_pom]"
          echo ::set-output name=has_pom::"$has_pom"
      - name: "Read java version"
        id: "java"
        if: steps.pom.outputs.has_pom == 'true'
        run: |
          java_version=$(./mvnw help:evaluate -Dexpression=java-version -q -DforceStdout)
          project_version=$(./mvnw help:evaluate -Dexpression=project.version -q -DforceStdout)
          has_publish_to_code_climate=$(if [[ "${{secrets.CC_TEST_REPORTER_ID}}" == "" ]]; then echo "false"; else echo "true"; fi)
          
          echo "java_version [$java_version]"
          echo "project_version [$project_version]"
          echo "has_publish_to_code_climate [$has_publish_to_code_climate]"
          
          echo ::set-output name=java_version::"$java_version"
          echo ::set-output name=project_version::"$project_version"
          echo ::set-output name=has_publish_to_code_climate::"$has_publish_to_code_climate"
      - name: "Setup java"
        if: steps.pom.outputs.has_pom == 'true'
        uses: actions/setup-java@main
        with:
          distribution: 'adopt'
          java-version: ${{ steps.java.outputs.java_version }}
      - name: "Resolve Maven Dependencies"
        id: "maven"
        if: steps.pom.outputs.has_pom == 'true'
        run: |
          ./mvnw -B -q dependency:resolve -Dmaven.test.skip=true
          ./mvnw -B -q dependency:resolve-plugins -Dmaven.test.skip=true
      - name: "Run Tests"
        if: steps.pom.outputs.has_pom == 'true'
        run: |
          ./mvnw -B -q clean verify
      - name: "Detect version change"
        id: "git"
        run: |
          git status;
          git checkout src/test/resources/diagram_example.svg &>/dev/null || true
          changes=$(git status --porcelain | grep version.txt | wc -l)
          has_changes=$(if [ "$changes" != "0" ]; then echo "true"; else echo "false"; fi)
          echo "changes [$changes]"
          echo "has_changes [$has_changes]"
          echo ::set-output name=has_changes::"$has_changes"
      - name: "Push changes"
        if: steps.git.outputs.has_changes == 'true'
        uses: stefanzweifel/git-auto-commit-action@master
        with:
          commit_message: "chore: 🔨 chore update version.txt"
          commit_user_name: "Kira"
          commit_user_email: "kira@yuna.berlin"
          commit_author: "Kira <kira@yuna.berlin>"
          skip_dirty_check: true
          skip_fetch: true
          skip_checkout: true
          disable_globbing: true
          create_branch: false
      - name: "Publish code quality"
        uses: paambaati/codeclimate-action@v3.0.0
        if: steps.java.outputs.has_publish_to_code_climate == 'true'
        env:
          CC_TEST_REPORTER_ID: ${{secrets.CC_TEST_REPORTER_ID}}
          JACOCO_SOURCE_PATH: "${{github.workspace}}/src/main/java"
        with:
          coverageLocations: ${{github.workspace}}/target/site/jacoco/jacoco.xml:jacoco
  test_outputs:
    needs: "test"
    runs-on: ubuntu-latest
    steps:
      - name: "print"
        run: |
          echo "-------------------- OUTPUTS --------------------"
          echo "has_pom                     [${{needs.test.outputs.has_pom}}]"
          echo "has_changes                 [${{needs.test.outputs.has_changes}}]"
          echo "java_version                [${{needs.test.outputs.java_version}}]"
          echo "project_version             [${{needs.test.outputs.project_version}}]"
          echo "has_publish_to_code_climate [${{needs.test.outputs.has_publish_to_code_climate}}]"
          echo "--------------------- ENVS ---------------------"
          env
