name: "[WC] Github Release Maven"
#description: "Creates a new GitHub release"
#designed: to be triggered after new tag creation
#TODO: Input: Changelog commit filter
#TODO: Filter duplicate commits

on:
  workflow_call:
    inputs:
      message:
        type: string
        description: "[message] release message [default: ${changelog}]"
        required: false
      artifacts_filter:
        type: string
        description: "[artifacts_filter] artifacts to append on the release [default: target/*.jar,build/*.jar]"
        required: false
    # Map the workflow outputs to job outputs
    outputs:
      has_pom:
        description: "[Boolean] if pom file exists"
        value: ${{ jobs.github_release.outputs.has_pom }}
      java_version:
        description: "[String] java version from pom file"
        value: ${{ jobs.github_release.outputs.java_version }}
      changelog:
        description: "[String] change log from release message"
        value: ${{ jobs.github_release.outputs.changelog }}
      latest_tag:
        description: "[String] latest tag"
        value: ${{ jobs.github_release.outputs.latest_tag }}
      second_latest_tag:
        description: "[String] second latest tag"
        value: ${{ jobs.github_release.outputs.second_latest_tag }}
jobs:
  read_version:
    runs-on: ubuntu-latest
    # Map the job outputs to step outputs
    outputs:
      latest_tag: ${{ steps.changelog.outputs.latest_tag }}
      second_latest_tag: ${{ steps.changelog.outputs.second_latest_tag }}
    steps:
      - name: "Validate Input"
        id: "inputs"
        run: |
          if [ "$GITHUB_ACTOR" != "YunaBraska" ]; then echo "Permission denied for user [$GITHUB_ACTOR]"; exit 1; fi
      - name: "Checkout"
        uses: actions/checkout@main
        with:
          fetch-depth: 500
          ref: ${{ steps.inputs.outputs.ref }}
      - name: "Read Tags"
        id: "changelog"
        run: |
          git fetch --all --tags
          latest_tag=$(git tag --sort=-creatordate | head -1)
          second_latest_tag=$(git tag --sort=-creatordate | head -2 | tail -1)
          
          echo "latest_tag [$latest_tag]"
          echo "second_latest_tag [$second_latest_tag]"
          
          echo "::set-output name=latest_tag::$latest_tag"
          echo "::set-output name=second_latest_tag::$second_latest_tag"
  github_release:
    needs: "read_version"
    runs-on: ubuntu-latest
    # Map the job outputs to step outputs
    outputs:
      has_pom: ${{ steps.pom.outputs.has_pom }}
      changelog: ${{ steps.changelog.outputs.changelog }}
      java_version: ${{ steps.java.outputs.java_version }}
      latest_tag: ${{ steps.changelog.outputs.latest_tag }}
      second_latest_tag: ${{ steps.changelog.outputs.second_latest_tag }}
    steps:
      - name: "Validate Input"
        id: "inputs"
        run: |
          if [ "$GITHUB_ACTOR" != "YunaBraska" ]; then echo "Permission denied for user [$GITHUB_ACTOR]"; exit 1; fi

          ref="${message_A:-${message_B:-${message_C:-""}}}"
          artifacts_filter="${artifacts_filter_A:-${artifacts_filter_B:-${artifacts_filter_C:-"target/*.jar,build/*.jar"}}}"

          echo "message [$message]"
          echo "artifacts_filter [$artifacts_filter]"

          echo "::set-output name=message::$message"
          echo "::set-output name=artifacts_filter::$artifacts_filter"
        env:
          message_A: ${{ inputs.message }}
          message_B: ${{ github.event.inputs.message }}
          message_C: ${{ github.event.client_payload.message }}
          artifacts_filter_A: ${{ inputs.artifacts_filter }}
          artifacts_filter_B: ${{ github.event.inputs.artifacts_filter }}
          artifacts_filter_C: ${{ github.event.client_payload.artifacts_filter }}
      - name: "Checkout"
        uses: actions/checkout@main
        with:
          fetch-depth: 500
          ref: ${{needs.read_version.outputs.latest_tag}}
      - name: "Locate POM"
        id: "pom"
        run: |
          has_pom=$([ -e "pom.xml" ] && echo "true" || echo "false") 
          echo "has_pom [$has_pom]"
          echo ::set-output name=has_pom::"$has_pom"
      - name: "Read java version"
        id: "java"
        if: steps.pom.outputs.has_pom == 'true'
        run: |
          java_version=$(./mvnw help:evaluate -Dexpression=java-version -q -DforceStdout)
          echo "java_version [$java_version]"
          echo ::set-output name=java_version::"$java_version"
      - name: "Setup java"
        if: steps.pom.outputs.has_pom == 'true'
        uses: actions/setup-java@main
        with:
          distribution: 'adopt'
          java-version: ${{ steps.java.outputs.java_version }}
      - name: "Resolve Maven Dependencies"
        id: "maven"
        if: steps.pom.outputs.has_pom == 'true'
        run: |
          ./mvnw -B -q dependency:resolve -Dmaven.test.skip=true
          ./mvnw -B -q dependency:resolve-plugins -Dmaven.test.skip=true
      - name: "Build App"
        if: steps.pom.outputs.has_pom == 'true'
        run: ./mvnw clean package -Dmaven.test.skip=true
      - name: "Get changelog"
        if: steps.pom.outputs.has_pom == 'true'
        id: "changelog"
        run: |
          latest_tag=${{needs.read_version.outputs.latest_tag}}
          second_latest_tag=${{needs.read_version.outputs.second_latest_tag}}

          mkdir -p target
          if [[ "$latest_tag" == "$second_latest_tag" ]]; then 
            git log --pretty=format:'- %s%n' > target/release.log
          else 
           git log --pretty=format:'- %s%n' $latest_tag..$second_latest_tag > target/release.log
          fi

          if [[ "${{ steps.inputs.outputs.message }}" != "" ]]; then
            echo "${{ steps.inputs.outputs.message }}" > target/release.log
          fi

          changelog=$(cat target/release.log)
          echo "latest_tag         [$latest_tag]"
          echo "second_latest_tag  [$second_latest_tag]"
          echo "target/release.log [$(cat target/release.log)]"
          echo "changelog          [$changelog]"

          echo "::set-output name=latest_tag::$latest_tag"
          echo "::set-output name=second_latest_tag::$second_latest_tag"
          echo "::set-output name=changelog::$changelog))"
      - name: "Print GitHub Release"
        run: |
          echo "latest_tag         [${{steps.changelog.outputs.latest_tag}}]"
          echo "second_latest_tag  [${{steps.changelog.outputs.second_latest_tag}}]"
          echo "target/release.log [$(cat target/release.log)]"
          echo "changelog          [${{steps.changelog.outputs.changelog}}]"
      - name: "Create GitHub Release"
        if: steps.pom.outputs.has_pom == 'true'
        id: "create_release"
        uses: ncipollo/release-action@main
        with:
          tag: ${{ steps.changelog.outputs.latest_tag }}
          artifacts: ${{ steps.inputs.outputs.artifacts_filter }}
          generateReleaseNotes: true
          bodyFile: target/release.log
          token: ${{ secrets.GITHUB_TOKEN }}
  release_outputs:
    needs: "github_release"
    runs-on: ubuntu-latest
    steps:
      - name: "print"
        run: |
          echo "-------------------- OUTPUTS --------------------"
          echo "has_pom           [${{needs.github_release.outputs.has_pom}}]"
          echo "java_version      [${{needs.github_release.outputs.java_version}}]"
          echo "changelog         [${{needs.github_release.outputs.changelog}}]"
          echo "latest_tag        [${{needs.github_release.outputs.latest_tag}}]"
          echo "second_latest_tag [${{needs.github_release.outputs.second_latest_tag}}]"
          echo "--------------------- ENVS ---------------------"
          env
