name: "[WC] Repo Update Java"
#TODO: Input: Branch/Tag/Commit

on:
  workflow_dispatch:
    inputs:
      ref:
        type: string
        description: "[ref] e.g. branch, tag or commit to checkout [default: github_ref_name || github_head_ref ]"
        required: false
  workflow_call:
    inputs:
      ref:
        type: string
        description: "[ref] e.g. branch, tag or commit to checkout [default: github_ref_name || github_head_ref ]"
        required: false
    # Map the workflow outputs to job outputs
    outputs:
      has_changes:
        description: "[Boolean] if git status has changes"
        value: ${{ jobs.update.outputs.has_changes }}
      java_version:
        description: "[String] java version from pom file"
        value: ${{ jobs.update.outputs.java_version }}
      project_version:
        description: "[String] project version from pom file"
        value: ${{ jobs.update.outputs.project_version }}
jobs:
  update:
    runs-on: ubuntu-latest
    # Map the job outputs to step outputs
    outputs:
      has_changes: ${{ steps.git.outputs.has_changes }}
      java_version: ${{ steps.java_info.outputs.java_version }}
      project_version: ${{ steps.java_info.outputs.project_version }}
    steps:
      - name: "Validate Input"
        id: "inputs"
        run: |
          if [ "$GITHUB_ACTOR" != "YunaBraska" ]; then echo "Permission denied for user [$GITHUB_ACTOR]"; exit 1; fi
          
          ref_default=${{ github.ref_name || github.head_ref }}
          ref="${ref_A:-${ref_B:-${ref_C:-${ref_default}}}}"
          
          echo "ref [$ref]"
          
          echo "ref=$ref" >> $GITHUB_OUTPUT
        env:
          ref_A: ${{ inputs.ref }}
          ref_B: ${{ github.event.inputs.ref }}
          ref_C: ${{ github.event.client_payload.ref }}
      - name: "Checkout"
        uses: actions/checkout@main
        with:
          ref: ${{ steps.inputs.outputs.ref }}
      - name: "Get Java Version"
        id: "java_info"
        uses: YunaBraska/java-info-action@main
      - name: "Setup java"
        uses: actions/setup-java@main
        if: steps.git.outputs.has_changes == 'true'
        with:
          distribution: 'adopt'
          java-version: ${{ steps.java_info.outputs.java_version }}
      - name: "Update Wrapper & Dependencies"
        run: |
          sh ${{ steps.java_info.outputs.cmd_update_wrapper }}
          sh ${{ steps.java_info.outputs.cmd_update_parent }}
          sh ${{ steps.java_info.outputs.cmd_update_props }}
      - name: "Detect changes"
        id: "git"
        run: |
          git add .;
          git status;
          has_changes=$(if [[ $(git status --porcelain) ]]; then echo "true"; else echo "false";fi)
          echo "changes [$(git status --porcelain | wc -l)]"
          echo "has_changes [$has_changes]"
          echo "has_changes=$has_changes" >> $GITHUB_OUTPUT
      - name: "Push changes"
        if: steps.git.outputs.has_changes == 'true'
        uses: stefanzweifel/git-auto-commit-action@master
        with:
          commit_message: "chore: 🔨 updated dependencies"
          commit_user_name: "Kira"
          commit_user_email: "kira@yuna.berlin"
          commit_author: "Kira <kira@yuna.berlin>"
          skip_dirty_check: true
          skip_fetch: true
          skip_checkout: true
          disable_globbing: true
          create_branch: false
  update_outputs:
    needs: "update"
    runs-on: ubuntu-latest
    steps:
      - name: "print"
        run: |
          echo "-------------------- OUTPUTS --------------------"
          echo "has_changes     [${{needs.update.outputs.has_changes}}]"
          echo "java_version    [${{needs.update.outputs.java_version}}]"
          echo "project_version [${{needs.update.outputs.project_version}}]"
          echo "--------------------- ENVS ---------------------"
          env
