name: "[WC] Repo Test Java"

on:
  workflow_dispatch:
    inputs:
      ref:
        type: string
        description: "[ref] e.g. branch, tag or commit to checkout [default: github_ref_name || github_head_ref ]"
        required: false
  workflow_call:
    inputs:
      ref:
        type: string
        description: "[ref] e.g. branch, tag or commit to checkout [default: github_ref_name || github_head_ref ]"
        required: false
    secrets:
      CC_TEST_REPORTER_ID:
        description: "Code Climate Id for test coverage and quality checks"
        required: false
    # Map the workflow outputs to job outputs
    outputs:
      has_changes:
        description: "[Boolean] if git status has changes"
        value: ${{ jobs.test.outputs.has_changes }}
      java_version:
        description: "[String] java version from pom file"
        value: ${{ jobs.test.outputs.java_version }}
      project_version:
        description: "[String] project version from pom file"
        value: ${{ jobs.test.outputs.project_version }}
      has_publish_to_code_climate:
        description: "[String] if code quality is pushed to code climate"
        value: ${{ jobs.test.outputs.has_publish_to_code_climate }}
jobs:
  test:
    runs-on: ubuntu-latest
    # Map the job outputs to step outputs
    outputs:
      has_changes: ${{ steps.git.outputs.has_changes }}
      java_version: ${{ steps.java_info.outputs.java_version }}
      project_version: ${{ steps.java_info.outputs.project_version }}
    steps:
      - name: "Checkout"
        uses: actions/checkout@main
        with:
          ref: ${{ inputs.ref || github.ref || github.ref_name || github.head_ref }}
      - name: "Get Java Version"
        id: "java_info"
        uses: YunaBraska/java-info-action@main
      - name: "Setup java"
        uses: actions/setup-java@main
        if: steps.git.outputs.has_changes == 'true'
        with:
          distribution: 'adopt'
          java-version: ${{ steps.java_info.outputs.java_version }}
      - name: "Resolve Plugins & Dependencies"
        run: |
          sh ${{ steps.java_info.outputs.cmd_resolve_deps }}
          sh ${{ steps.java_info.outputs.cmd_resolve_plugs }}
      - name: "Run Tests"
        run: sh ${{ steps.java_info.outputs.cmd_test }}
      - name: "Detect version change"
        id: "git"
        run: |
          git status;
          git checkout src/test/resources/diagram_example.svg &>/dev/null || true
          changes=$(git status --porcelain | grep version.txt | wc -l)
          has_changes=$(if [ "$changes" != "0" ]; then echo "true"; else echo "false"; fi)
          echo "changes [$changes]"
          echo "has_changes [$has_changes]"
          echo "has_changes=$has_changes" >> $GITHUB_OUTPUT
      - name: "Push changes"
        if: steps.git.outputs.has_changes == 'true'
        uses: stefanzweifel/git-auto-commit-action@master
        with:
          commit_message: "chore: 🔨 chore update version.txt"
          commit_user_name: "Kira"
          commit_user_email: "kira@yuna.berlin"
          commit_author: "Kira <kira@yuna.berlin>"
          skip_dirty_check: true
          skip_fetch: true
          skip_checkout: true
          disable_globbing: true
          create_branch: false
      - name: "Publish code quality"
        uses: paambaati/codeclimate-action@main
        if: secrets.CC_TEST_REPORTER_ID
        env:
          CC_TEST_REPORTER_ID: ${{secrets.CC_TEST_REPORTER_ID}}
          JACOCO_SOURCE_PATH: "${{github.workspace}}/src/main/java"
        with:
          coverageLocations: ${{github.workspace}}/target/site/jacoco/jacoco.xml:jacoco
  test_outputs:
    needs: "test"
    runs-on: ubuntu-latest
    steps:
      - name: "print"
        run: |
          echo "-------------------- OUTPUTS --------------------"
          echo "has_changes                 [${{needs.test.outputs.has_changes}}]"
          echo "java_version                [${{needs.test.outputs.java_version}}]"
          echo "project_version             [${{needs.test.outputs.project_version}}]"
          echo "--------------------- ENVS ---------------------"
          env
