name: "[WC] Update Workflow"

on:
  workflow_call:
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: "Check Permission"
        run: |
          if [ "$GITHUB_ACTOR" != "YunaBraska" ]; then echo "Permission denied for user [$GITHUB_ACTOR]"; exit 1; fi
      - name: "Checkout"
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref_name || github.head_ref }}
          token: ${{ secrets.CI_TOKEN_WORKFLOW || github.token }}
      - name: Run GitHub Actions Version Updater
        uses: saadmk11/github-actions-version-updater@v0.5.6
        with:
          committer_username: 'Kira'
          committer_email: 'kira@yuna.berlin'
          commit_message: "chore: 🔨 updated workflow"
          pull_request_title: "core/update/workflow"
          token: "invalid_next_plugin_will_push_changes"
      - name: "Detect changes"
        id: "git"
        run: |
          has_changes="false"
          default_branch=$(git rev-parse --abbrev-ref origin/HEAD)
          echo "default_branch [$default_branch]"
          current_branch=$(git rev-parse HEAD)
          echo "current_branch [$current_branch]"
          changes=$(git diff --name-only $(default_branch)...$(current_branch) | wc -l)
          if [ "$changes" != "0" ]; then 
            git reset head^
            git stash
            git add .
            git checkout ${{ github.ref_name || github.head_ref }}
            git stash pop
            has_changes="true"
          fi 
          echo "number of changes [$(git status --porcelain | wc -l)]"
          echo "has_changes [$has_changes]"
          echo ::set-output name=has_changes::"$has_changes"
      - name: "Push changes"
#        if: steps.git.outputs.has_changes == 'true'
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore: 🔨 updated workflow"
          commit_user_name: "Kira"
          commit_user_email: "kira@yuna.berlin"
          commit_author: "Kira <kira@yuna.berlin>"
          skip_dirty_check: true
          skip_fetch: true
          skip_checkout: true
          disable_globbing: true
          create_branch: false
          branch: ${{ github.ref_name || github.head_ref }}
  update_outputs:
    needs: "update"
    runs-on: ubuntu-latest
    steps:
      - name: "print"
        run: |
          echo "---------- OUTPUTS ----------"
          echo N/A
          echo "----------- ENVS -----------"
          env
